# https://github.com/marketplace/actions/github-labeler
---
# Type labels
- name: "type: bug"
  color: "d73a4a"
  description: "Something isn't working"
- name: "type: documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"
- name: "type: enhancement"
  color: "a22eef"
  description: "New feature or request"
- name: "type: question"
  color: "d876e3"
  description: "Further information is requested"
- name: "type: dependencies"
  color: "b4a8d1"
  description: "Pull requests that update a dependency file"
- name: "type: todo"
  color: "00B0D8"
  description: "Todo issue"
- name: "type: wip"
  color: "fbca04"
  description: "Work in progress"

# Status labels
- name: "status: on-hold"
  color": "fef2c0"
  description: "This issue or pull request is on hold"
- name: "status: wontfix"
  color: "ffffff"
  description: "This will not be worked on"
- name: "status: needs information"
  color": "fef2c0"
  description: "Further information is required"
- name: "status: duplicate"
  color: "cfd8d7"
  description: "This issue or pull request already exists"
- name: "status: confirmed"
  color: "0e8a16"
  description: "Issue confirmed"
- name: "status: can't reproduce"
  color: "fec1c1"
  description: "Unable to reproduce"
- name: "status: invalid"
  color: "e4e669"
  description: "This doesn't seem right"
- name: "status: needs review"
  color: "334796"
  description: "Pull request needs manual review"
- name: "status: approved"
  color: "0e8a16"
  description: "Pull request is approved"
- name: "status: has conflicts"
  color: "000000"
  description: "Pull requests has conflicts"
- name: "status: needs triage"
  color: "0e8a16"
  description: "Issue needs manual triage"
- name: "status: stale"
  color: "eeeeee"
  description: "Stale issue"
- name: "status: changes requested"
  color: "aa2626"
  description: "Pull request changes requested"
- name: "status: merged"
  color: "6f42c1"
  description: "Pull request merged"

# Warning lables
- name: "warn: lfs detected"
  color: "ff1493"
  description: "Warning Label for use when LFS is detected in the commits of a Pull Request"

# Size labels
- name: "size: xs"
  color: "00ff3a"
  description: "Pull request has less then 10 lines"
- name: "size: s"
  color: "9cff00"
  description: "Pull request has 10 to 30 lines"
- name: "size: m"
  color: "efff00"
  description: "Pull request has 30 to 100 lines"
- name: "size: l"
  color: "ff7500"
  description: "Pull request has 100 to 500 lines"
- name: "size: xl"
  color: "c60404"
  description: "Pull request has 500 to 1000 lines"
- name: "size: xxl"
  color: "b60205"
  description: "Pull request has more then 1000 lines"

# Priority labels
- name: "priority: critical"
  color: "b60205"
  description: "Priority is critical"
- name: "priority: high"
  color: "d93f0b"
  description: "Priority is high"
- name: "priority: medium"
  color: "fbca04"
  description: "Priority is medium"
- name: "priority: low"
  color: "0e8a16"
  description: "Priority is low"

# Project specific scope labels
- name: "scope: project"
  color: "bfe5bf"
  description: "Modify root"
- name: "scope: tests"
  color: "bfe5bf"
  description: "Modify test sources"
- name: "scope: ci"
  color: "bfe5bf"
  description: "Modify ci configuration"
- name: "scope: docs"
  color: "bfe5bf"
  description: "Modify documentation"

# Various labels
- name: "help wanted"
  color: "12ba0c"
  description: "Contributing help wanted"
