---
name: Issue triage

on:
  issues:
    types: [opened, unassigned]

jobs:
  labels:
    runs-on: ubuntu-latest
    name: Add lables
    steps:
      - name: Add triage label if not assigned
        if: contains(github.event.issue, 'assignee') == false
        uses: actions-ecosystem/action-add-labels@v1.1.3
        with:
          labels: "status: needs triage"
