---
name: Pull request cleanup

on:
  pull_request:
    branches:
      - dev
    types: [closed]

jobs:
  handle-labels:
    runs-on: ubuntu-latest
    name: Handle labels
    steps:
      - name: Remove triage label
        uses: actions-ecosystem/action-remove-labels@v1.1.0
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "status: needs triage"

      - name: Remove review label
        uses: actions-ecosystem/action-remove-labels@v1.1.0
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "status: needs review"

      - name: Add merged label if merged
        if: github.event.pull_request.merged == true
        uses: actions-ecosystem/action-add-labels@v1.1.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: "status: merged"

  handle-pr:
    runs-on: ubuntu-latest
    name: Handle pull request
    steps:
      - name: Lock pull request
        uses: dessant/lock-threads@v2.0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-lock-comment: "Locking this pull request."
          process-only: prs
