---
name: Pull request content
on:
  pull_request_target:
    branches:
      - dev
    types: [opened, edited, synchronize]

permissions:
  pull-requests: write

jobs:
  label-by-content:
    runs-on: ubuntu-latest
    name: Label by content
    steps:
      - name: Source checkout
        uses: actions/checkout@v2.4.0
        with:
          ref: ${{ github.head_ref }}

      - name: Label scope by content
        uses: actions/labeler@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: ".github/configs/content_labels.yml"
          sync-labels: true

      - name: Label if conflicts found
        uses: mschilde/auto-label-merge-conflicts@v2.0
        with:
          CONFLICT_LABEL_NAME: "status: has conflicts"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Label if contains large files
        uses: actionsdesk/lfs-warning@v3.1
        with:
          labelName: "warn: lfs detected"
          filesizelimit: "1mb"
