---
name: Pull request triage

on:
  pull_request_target:
    branches:
      - dev
    types: [opened]

permissions:
  pull-requests: write

jobs:
  triage-non-bots:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]' && github.actor != 'allcontributors[bot]'
    name: Triage non bots
    steps:
      - name: Set reviewers and assign author
        uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          configuration-path: ".github/configs/auto_assign.yml"

      - name: Add review label
        uses: actions-ecosystem/action-add-labels@v1.1.3
        with:
          labels: "status: needs review"

  triage-by-bots:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'allcontributors[bot]'
    name: Triage by bots
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v2.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add approved label
        uses: actions-ecosystem/action-add-labels@v1.1.3
        with:
          labels: "status: approved"
