---
name: Repository management

on:
  push:
    branches:
      - dev

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    name: Sync repository labels
    steps:
      - name: Source checkout
        uses: actions/checkout@v2.4.0

      - name: Verify labels
        uses: crazy-max/ghaction-github-labeler@v3.1.1
        with:
          yaml-file: ".github/configs/synced_labels.yml"
