---
name: Pull request triage

on:
  pull_request_target:
    branches:
      - dev
    types: [opened]

permissions:
  pull-requests: write

jobs:
  triage:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || github.actor == 'allcontributors[bot]'
    name: Pull request triage
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v2.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
